* MILP PA Frontiers Paper
This paper discusses the research behind the Mixed Integer Linear Program (MILP) solution to the Position Allocation
Problem (PAP). The paper, as the name suggests is configured to be submitted for the [[https://www.frontiersin.org/][Frontiers journal]]. This paper
contains some significant improvements to its [[https://github.com/alexb7711/milp-pap][predecessor]].

* Building the Document
To build the document, it is recommended to have a full \LaTeX implementation. The user must also have [[https://mg.readthedocs.io/latexmk.html][=latexmk=]]
installed. After the dependencies have been installed, simply make the PDF by typing =make= in a terminal. The first
time the project is built it will:

- ensure all dependencies have been installed
- compiles all the figures
- compiles the document

The first build takes a while because of the figures. The only times that the figures need to be recompiled is if the
=./img/data/= directory has been updated. The data is generated by running the [[https://github.com/alexb7711/milp-pap][MILP PAP project]].
