* MILP PAP Frontiers Paper
This paper discusses the research behind the Mixed Integer Linear Program (MILP) solution to the Position Allocation
Problem (PAP). The paper, as the name suggests, is configured to be submitted for the [[https://www.frontiersin.org/][Frontiers journal]]. It also 
contains some significant improvements, as well as vital corrections, to its [[https://github.com/alexb7711/milp-pap][predecessor]].

* Building the Document
To build the document, it is recommended to have a full \LaTeX implementation. It is also recommended that [[https://taskfile.dev/installation/][go-task]] 
in installed. The user must also have [[https://mg.readthedocs.io/latexmk.html][=latexmk=]] installed. Note that =Taskfile.yml= has checks for dependencies.
After the dependencies have been installed, the PDF can be built by typing =task= (or =go-task=) in a terminal. The first time the project is built it will:

- ensure all dependencies have been installed
- compiles all the figures
- compiles the document

The first build takes a while because of the figures. The only times that the figures need to be recompiled is if the
=./img/data/= directory has been updated. The data is generated by running the [[https://github.com/alexb7711/milp-pap][MILP PAP project]].

** Project Structure
Because a lot of the figures are build using [[https://tikz.dev/][tikz]], a lot of space is taken up with the figure code. All the generated images are found
in the =img/= directory. Also for the sake of modularity, reusability (hopefully some of these modules are used in my thesis), and my own sanity of buffer 
sizes while editing, the sections have also been broken down in the =tex/= directory. These files are "put together" in =main.tex=.
