version: '3'

################################################################################
# ENVIRONTMENT
################################################################################
env:
  TARGET : a-position-allocation-approach-to-the-scheduling-of-beb-charging.pdf
  IMG_DIR: ./img
  DOC    : main    																															# Name of main source file

################################################################################
# RECIPES
################################################################################

##==============================================================================
#
tasks:
  default:
    cmds:
      - task: precheck
      - task: images
      - task: pdf

##==============================================================================
#
  pipeline:
    cmds:
      - task: precheck
      - task: images
      - task: set-version
      - task: pdf
##==============================================================================
#
  precheck:
    desc: "Make sure that all the dependencies are installed."
    cmds:
      - |
        echo "Checking the programs required for the build are installed..."
        latexmk --version >/dev/null 2>&1 && (echo "latexmk installed!") || (echo "ERROR: latexmk is required."; exit 1)
        pdflatex --version >/dev/null 2>&1 && (echo "pdflatex installed!") || (echo "ERROR: pdflatex is required."; exit 1)
    silent: true

##==============================================================================
#
  images:
    desc: "Creates a PDF of all the files in {{.IMGDIR}}."
    sources:
      - ./img/*.tex
    generates:
      - ./img/*.pdf
    vars:
      IMG_SRC:
        sh: ls {{.IMG_DIR}} | grep ".tex$"
    cmds:
      - |
        for i in {{.IMG_SRC | catLines}}
        do
          pdflatex -shell-escape -interaction=nonstopmode -output-directory {{.IMG_DIR}} ${i}
        done
    silent: true

##==============================================================================
# Resources:
# - https://stackoverflow.com/questions/15559359/insert-line-after-match-using-sed
#
  set-version:
    desc: "Dynamically sets the version of the document."
    vars:
      ABSTRACT: sections/abstract.tex
      VERSION:
        sh: git describe --tags
    cmds:
      - |
        grep {{.VERSION}} {{.ABSTRACT}} > /dev/null || \
        sed -i 's/\\begin{abstract}/\\begin{abstract}\nVERSION: \\today:{{.VERSION}}\n/' {{.ABSTRACT}}
    silent: true

##==============================================================================
#
  relative-path-bibtex:
    desc: "Update the paths in the 'bibtex' command to be relative."
    cmds:
      - sh scripts/relative-path-bibtex

##==============================================================================
#
  pdf:
    desc: "Output {{.TARGET}} PDF."
    cmds:
      - task: relative-path-bibtex
      - |
        ! [ -x "$(epspdf -v)" ] && epspdf logo1.eps || eps2pdf logo1.eps
        mv logo1.pdf logo1-eps-converted-to.pdf
        latexmk -f -interaction=nonstopmode \
                   -pdf -pdflatex="pdflatex --shell-escape %O %S" \
                   -bibtex {{.DOC}}.tex
        [ -f {{.DOC}}.pdf ] && mv main.pdf {{.TARGET}}
    silent: true

##==============================================================================
#
  clean:
    desc: "Clean up the project."
    vars:
      DOC_SRC: main.tex
    cmds:
      - |
        for f in $(find {{.IMG_DIR}} -maxdepth 1 -type f)
        do
          [ ${f##*.} != "tex" ] && rm ${f}
        done
        rm -f {{.TARGET}}
        latexmk -silent -C {{.DOC_SRC}}
    silent: true
