* Conclusion
:PROPERTIES:
:custom_id: sec:conclusion
:END:

This work developed a MILP scheduling framework that optimally assigns fast and slow chargers to a BEB bus fleet
assuming a constant schedule. The BAP was briefly introduced followed by a description and formulation of the PAP. The
PAP was modified to allow charge time to be variable. Because the modified PAP no longer requires the charge time to be
given, linear battery dynamics were introduced to propagate each BEBs' SOC. Additional constraints were also introduced
to provide upper and lower limits for the battery dynamics.

An example for the MILP PAP formulation was then presented and compared to a heuristic-based schedule, referred to as
Qin-Modified. The MILP PAP optimization was run for \timeran seconds to a non-optimal solution. The Qin-Modified and
MILP schedule utilized a similar amount of fast chargers; however, the MILP schedule more readily used the slow chargers
to its advantage when the objective function saw fit. More importantly, the MILP PAP schedule utilized approximately
$0.1\cdot10^4$ kWh more than the Qin-Modified; however, the charges for the MILP schedule remained above the constrained
minimum SOC of \mincharge, and charged all the buses to \fpeval{\bcharge *100}% at the end of the working day. The
Qin-Modified schedule, on the other hand, allowed the SOC of certain BEBs to drop to 0\%.

Further fields of interest are to utilize the formulation (\autoref{eq:objective} and \autoref{eq:dynconstrs}) with
nonlinear battery dynamics, calculation and utilization of the demand and consumption cost in the objective function,
and utilizing this formulation in a metaheuristic solver. Furthermore, ``fuzzifying'' the initial and final charge times
is of interest to allow flexibility in the arrival and departure times.

#  LocalWords:  MILP metaheuristic fuzzifying BEB
