* Example
:PROPERTIES:
:custom_id: sec:example
:END:

An example will now be presented to demonstrate the utility of the developed MILP charge scheduling technique. A
description of the scenario is first presented followed a description of an alternative heuristic based planning
strategy called Quin-Modified which is used as a comparison to the MILP PAP. Results are then presented for each of
planning strategies are presented, analyzed, and discussed.

** BEB Scenario
:PROPERTIES:
:custom_id: beb-scenario
:END:

To display the capabilities of the model, an example scenario is presented. The scenario was run over a time horizon of
$T=24$ hours, utilizes $n_B = \A$ buses with $n_V = \N$ visits to the station divided between the $n_B$ buses. As stated
before, the route times are sampled from a set of routes from the UTA. Each bus has \batsize KWh battery that is
required to stay above \mincharge charge (\fpeval{\batsize * \minchargeD} KWh) to maintain battery health. Each bus is
assumed to begin the working day with \fpeval{\acharge*100}\% charge (\fpeval{\acharge * \batsize} KWh). Additionally,
each bus is required to end the day with a minimum charge of \fpeval{\bcharge * 100}\% (\fpeval{\bcharge * \batsize}
KWh). Each bus is assumed to discharge at a rate of 30 KW. Note that there are many factors that play a role in the
rate of discharge; however, for the sake of simplicity an average rate is used. $n_C = \fpeval{\fast + \slow}$ chargers
are utilized where \slow of the chargers are slow charging (\slows KW) and \fast are fast charging (\fasts KW). A
technique to minimize chargers will be employed.

To encourage the MILP PAP problem to utilize the fewest number of chargers, the value of $m_q$ in the objective
function, \autoref{eq:objective}, is $\forall q \in n_Q; m_q = 1000q$. The charge duration scalar, $\epsilon_q$, is defined as
$\epsilon_q = r_q$ to create a consumption cost term, $g_{iq}\epsilon_q$. This is utilized to also encourage the model to minimize
active charger times, particularly for the fast chargers.

Another heuristic-based optimization strategy, referred to as Quin-Modified, is also employed as a means of comparison
with the results of the MILP PAP. The Quin-Modified strategies is a based on the threshold strategy of
[cite:@qin-2016-numer-analy]. The strategy has been modified slightly to accommodate the case of multiple charger types
and without exhaustive search for the best charger type. The heuristic is based on a set of rules that revolve around
the initial charge of the bus at visit $i$. There are three different thresholds, low (60\%), medium (75\%), and high
(90\%). Buses below the low threshold are prioritized to fast chargers then are allowed to utilize slow chargers if no
fast chargers are available. Buses between the low and medium threshold prioritize slow chargers first and utilize fast
chargers only if no slow chargers are available. Buses above the medium threshold and below high will only be assigned
to slow chargers. Buses above the high threshold will not be charged. Once a bus has been assigned to a charger, it
remains on the charger for the duration of the time it is at the station, or it reaches 90\% charge, whichever comes
first.

UTA bus routing data that occurs over a 24-hour time period. The total number of constraints resulted in \contvars
continuous and \intvars integer/binary constraints. The optimization was performed using the Gurobi MILP solver
[cite:@gurobi-2021-gurob-optim] on a machine running an AMD Ryzen 9 5900X 12 - Processor (24 core) at 4.95GHz. The
solver was allowed to run for \timeran seconds.

** Results
:PROPERTIES:
:custom_id: results
:END:

The schedule generated by the Quin-Modified strategy and the MILP PAP is shown in \autoref{subfig:quin-schedule} and
\autoref{subfig:milp-schedule}, respectively. The x-axis represents the time in hours. The y-axis represents the
assigned charging queue. Rows between 0 and \fpeval{\slow - 1} are active times for slow chargers, and rows in the range
of \fpeval{\slow - 1} and \fpeval{\fast + \slow - 1} are active times for fast chargers. The unique color/symbol styled
vertices represents the starting charge time for a bus $b$ with the line to the vertical tick signifying the region of
time the charger is active. The line connecting points represent the charge sequence for a bus.

The first observation is in the choice of preferred chargers between the Quin-Modified and MILP scheduler. Looking at
\autoref{subfig:slow-charger-usage} and \autoref{subfig:fast-charger-usage}, the Quin-Modified schedule uses at most
four fast chargers and three slow at the same time, whereas the MILP schedule uses at most two fast chargers and four
slow at the same time. \autoref{subfig:milp-schedule} shows a few outliers for the selected fast chargers. Both the
Quin-Modified and MILP schedule used the fast chargers in short bursts (~0.2-0.5 hours). The main difference lies in the
utilization strategy of the slow chargers. The Quin-Modified, for the most part, opted for shorter bursts for the slow
chargers (~0.3-0.7 hour), most heavily placed on the first slow charger. The MILP also used these shorter charge times
on the first slow charger; however, the schedule was able to recognize the bus routes that had longer a duration at the
station and could choose the lower cost option, slow charging, when available and of lower cost. Although one the MILP's
objectives is to minimize the amount of chargers used, the Quin-Modified schedule ended up using the same amount of
total chargers as the MILP. Note the MILP schedule packed the first queue for the fast and slow chargers more
effectively than the Quin schedule. Although both schedules generated are valid, no comparison of the quality the
schedule can be made directly from \autoref{subfig:milp-schedule} and \autoref{subfig:quin-schedule}.

\autoref{subfig:quin-charge} and \autoref{subfig:milp-charge} depicts the charge for every bus over the time horizon.
Every vehicle begins at 90% charge, finishes at \fpeval{\bcharge *100}% charge in the MILP PAP schedule, and never goes
below \mincharge in the intermediate arrivals as stated in the constraints \autoref{eq:dynconstrs}. There is no
guarantee for this in the Quin-Modified strategy which can be seen by some of the bus charges reaching a charge of 0% as
well as the distribution of final charges. The only sense of guarantee that the Quin-Modified supplies is its
predictability within the intermediate visits because of the heuristic nature (i.e. if the BEB charge is within the low
threshold, a fast charger will be prioritized) whereas MILP places a bus in the queue that ``makes sense'' in respect to
the larger picture. The MILP PAP does not have an obvious sense of decision-making due to its weighted decisions that
are affected by the accumulation of decisions made prior.

Another important measure for the chargers is to compare the amount of power and energy consumed.
\autoref{fig:power-usage} depicts the power consumption throughout the time horizon. It can be seen that the
Quin-Modified power consumption is steadily less or the same as the MILP schedule. This can be accounted for by the
MILP's constraints to keep the bus charges above \mincharge and to reach the \fpeval{\bcharge *100}% charge at the end
of the working day. It is also important to note that largest peak for the Quin-Modified schedule verses the lack of any
real peak for the MILP PAP schedule. Although the MILP PAP had firmer constraints than the Quin-Modified algorithm, it
maintained a steady power consumption profile throughout the time horizon. Along a similar vein, the accumulated energy
consumed is shown in \autoref{fig:energy-usage}. The MILP schedule is more efficient up until about hour 11. Again, this
can be accounted for by the fact the MILP is accommodating the extra constraints. Even with these constraints, MILP PAP
consumes about $1\cdot10^5$ KWh more than the Quin-Modified. The overlap of the MILP PAP can be accounted for by
\autoref{subfig:fast-charger-usage} and \autoref{subfig:slow-charger-usage}. Between the fifth and tenth hour, the MILP
schedule heavily uses slow chargers increasing the rate at which power is being consumed. Afterwards, the MILP schedule
at a minimum continues to use the same amount of chargers as the Quin Schedule. Again, due to the added constraints, the
MILP schedule must utilize more resources to keep within the specified bounds.

#  LocalWords:  MILP MILP's Gurobi Ryzen BEB
