* Example
:PROPERTIES:
:custom_id: sec:example
:END:

An example will now be presented to demonstrate the utility of the developed MILP charge scheduling technique. A
description of the scenario is first presented followed by a description of an alternative heuristic-based planning
strategy called Qin-Modified which is used as a comparison to the MILP PAP. Results are then presented for each of the
planning strategies are presented, analyzed, and discussed.

** BEB Scenario
:PROPERTIES:
:custom_id: beb-scenario
:END:

To display the capabilities of the model, an example scenario is presented. The scenario was run over a time horizon of
$T=24$ hours, utilizing $n_B = \A$ buses with $n_V = \N$ visits to the station divided between the $n_B$ buses. As
stated before, the route times are sampled from a set of routes from the UTA. Each bus has \batsize KWh battery that is
required to stay above \mincharge charge (\fpeval{\batsize * \minchargeD} KWh) to maintain battery health. Each bus is
assumed to begin the working day with a \fpeval{\acharge*100}% charge (\fpeval{\acharge * \batsize} KWh). Additionally,
each bus is required to end the day with a minimum charge of \fpeval{\bcharge * 100}% (\fpeval{\bcharge * \batsize}
KWh). This assumes that overnight charging can account for at least 20% of the charge. Each bus is assumed to discharge
at a rate of 30 KW. Note that many factors play a role in the rate of discharge; however, for the sake of simplicity, an
average rate is used. $n_C = \fpeval{\fast + \slow}$ chargers are utilized where \slow of the chargers are slow charging
(\slows KW) and \fast are fast charging (\fasts KW). A technique to minimize chargers will be employed.

src_latex{\hl{To encourage the MILP PAP problem to utilize the fewest number of chargers, the value of $m_q$ in the
objective function, {\autoref{eq:objective}}, is $\forall q \in \{1,2,..., n_B \}; m_q = 0$ and $\forall q \in \{n_B + 1, n_B + 2,...,
n_B + n_C \}; m_q = 1000q$.}} The charge duration scalar, $\epsilon_q$, is defined as $\epsilon_q = r_q$ to create a consumption cost
term, $g_{iq}\epsilon_q$. This is utilized to also encourage the model to minimize active charger times, particularly for the
fast chargers.

Another heuristic-based optimization strategy, referred to as Qin-Modified, is also employed as a means of comparison
with the results of the MILP PAP. The Qin-Modified strategy is based on the threshold strategy of
[cite:@qin-2016-numer-analy]. The strategy has been modified slightly to accommodate the case of multiple charger types
without an exhaustive search for the best charger type. The heuristic is based on a set of rules that revolve around the
initial charge of the bus at visit $i$. There are three different thresholds, low (85%), medium (90%), and high (95%).
Buses below the low threshold are prioritized to fast chargers and then are allowed to utilize slow chargers if no fast
chargers are available. Buses between the low and medium threshold prioritize slow chargers first and utilize fast
chargers only if no slow chargers are available. Buses above the medium threshold and below the high will only be
assigned to slow chargers. Buses above the high threshold will not be charged. Once a bus has been assigned to a
charger, it remains on the charger for the duration of the time it is at the station, or it reaches 95% charge,
whichever comes first.

UTA bus routing data that occurs over a 24-hour time horizon. The total number of constraints resulted in \contvars
continuous and \intvars integer/binary constraints. The optimization was performed using the Gurobi MILP solver
[cite:@gurobi-2021-gurob-optim] on a machine running an AMD Ryzen 9 5900X 12 - Processor (24 core) at 4.95GHz. The
solver was allowed to run for \timeran seconds.

** Results
:PROPERTIES:
:custom_id: results
:END:

The schedule generated by the Qin-Modified strategy and the MILP PAP is shown in \autoref{subfig:qin-schedule} and
\autoref{subfig:milp-schedule}, respectively. The x-axis represents the time in hours. The y-axis represents the
assigned charging queue. Rows between 0 and \fpeval{\slow - 1} are active times for slow chargers, and rows in the range
of \fpeval{\slow - 1} and \fpeval{\fast + \slow - 1} are active times for fast chargers. The unique color/symbol-styled
vertices represent the starting charge time for a bus $b$ with the line to the vertical tick signifying the region of
time the charger is active. The lines connecting points represents the charge sequence for each BEB.

The first observation is in the choice of preferred chargers between the Qin-Modified and MILP scheduler. Looking at
\autoref{subfig:slow-charger-usage} and \autoref{subfig:fast-charger-usage}, the Qin-Modified schedule uses at most four
fast chargers and three slow at the same time, whereas the MILP schedule uses at most one fast charger and six slow at
the same time. Both the Qin-Modified and MILP schedule used the fast chargers in short bursts (~0.2-0.5 hours). The main
difference lies in the utilization strategy of the slow chargers. The Qin-Modified, for the most part, opted for shorter
bursts for the slow chargers (~0.3-0.7 hours), most heavily placed on the first slow charger. The MILP also used these
shorter charge times on the first slow charger; however, the schedule was able to recognize the bus routes that had a
longer duration at the station and could choose the lower cost option, slow charging, when available and of lower cost.
Although one of the MILP's objectives is to minimize the amount of chargers used, the Qin-Modified schedule ended up
using the same amount of total chargers as the MILP. Note the MILP schedule packed the first queue for the fast and slow
chargers more effectively than the Qin schedule. Although both schedules generated are valid, no comparison of the
quality of the schedule can be made directly from \autoref{subfig:milp-schedule} and \autoref{subfig:qin-schedule}.

\autoref{subfig:qin-charge} and \autoref{subfig:milp-charge} depicts the charge for every bus over the time horizon.
Every vehicle begins at 90% charge, finishes at \fpeval{\bcharge *100}% charge in the MILP PAP schedule, and never goes
below \mincharge in the intermediate arrivals as stated in the constraints \autoref{eq:dynconstrs}. There is no
guarantee for this in the Qin-Modified strategy which can be seen by some of the bus charges reaching a charge of 0% as
well as the distribution of final charges, the minimum being 0% and the maximum @@latex: \fpeval{ trunc(\fpeval{368 /
\batsize * 100}, 3) }@@%. The only sense of guarantee that the Qin-Modified supplies is its predictability within the
intermediate visits because of the heuristic nature (i.e. if the BEB charge is within the low threshold, a fast charger
will be prioritized) whereas MILP places a bus in the queue that ``makes sense'' in respect to the larger picture. The
MILP PAP does not have an obvious sense of decision-making due to its weighted decisions that are affected by the
accumulation of decisions made prior.

Another important measure for the chargers is to compare the amount of power and energy consumed.
\autoref{fig:power-usage} depicts the power consumption throughout the time horizon. It can be seen that the
Qin-Modified power consumption is steadily less or the same as the MILP schedule. This can be accounted for by the
MILP's constraints to keep the bus charges above \mincharge and to reach the \fpeval{\bcharge *100}% charge at the end
of the working day. It is also important to note that the largest peak for the Qin-Modified schedule. Although the MILP
PAP had firmer constraints than the Qin-Modified algorithm, it maintained a steadier power consumption profile
throughout the time horizon. Along a similar vein, the accumulated energy consumed is shown in
\autoref{fig:energy-usage}. The MILP schedule is more efficient up until about hour 11. Again, this can be accounted for
by the fact the MILP is accommodating the extra constraints. Even with these constraints, MILP PAP consumes about
$1\cdot10^5$ KWh more than the Qin-Modified. The overlap of the MILP PAP can be accounted for by
\autoref{subfig:fast-charger-usage} and \autoref{subfig:slow-charger-usage}. Between the fifth and tenth hour, the MILP
schedule heavily uses slow chargers increasing the rate at which power is being consumed. Afterwards, the MILP schedule
at a minimum continues to use the same amount of chargers as the Qin Schedule. Again, due to the added constraints, the
MILP schedule must utilize more resources to keep within the specified bounds.

#  LocalWords:  MILP MILP's Gurobi Ryzen BEB
