name: LaTeX Release

on:
  push:
    tags: 'v*.**'

jobs:
  pre-release:
    name: "Release"
    runs-on: ubuntu-latest
    steps:
    - uses: https://github.com/actions/checkout@v3
      with:
        submodules: true
    - run: sudo apt-get update && sudo apt-get install -y texlive-full latexmk
    - uses: https://github.com/arduino/setup-task@v1
    - run: task clean && task pipeline
    - uses: https://github.com/ncipollo/release-action@v1
      with:
        artifacts: "a-position-allocation-approach-to-the-scheduling-of-beb-charging.pdf"
        bodyFile: "README.org"
