name: LaTeX Release

on:
  push:
    branches: [ "main" ]

jobs:
  call-workflow-in-local-repo:
    uses: ./.github/workflows/build-pdf.yml

  pre-release:
    name: "Pre Release"
    needs: call-workflow-in-local-repo
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@v3
      with:
        name: artifact
    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Early Release Draft"
          files: ./a-position-allocation-approach-to-the-scheduling-of-beb-charging.pdf
            
